workflows:
  flutter-android:
    name: Flutter Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      android: latest
      vars:
        PACKAGE_NAME: "com.systex.wms" # ajuste para o id do app
        CM_KEYSTORE: Encrypted(...)     # 🔐 será configurado no Codemagic
        CM_KEYSTORE_PASSWORD: Encrypted(...)
        CM_KEY_ALIAS: Encrypted(...)
        CM_KEY_PASSWORD: Encrypted(...)
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Analyze project
        script: flutter analyze
      - name: Run tests
        script: flutter test
      - name: Build APK (release)
        script: flutter build apk --release
      - name: Build AppBundle (release)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - "manoel.filho.mf@"
        notify:
          success: true
          failure: true
